# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: reject_submission

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  reject:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install challengeutils

    - name: Reject Submissions
      run: |
        python scripts/reject_submissions.py --username ${{ secrets.SYN_USERNAME }} --password ${{ secrets.SYN_PASSWORD }}
